---
abstract: 'Interface to the Docker API'
author:
  - 'Peter Stuifzand <peter@stuifzand.eu>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: 0.025
dynamic_config: 0
generated_by: 'Dist::Milla version v0.9.7, Dist::Zilla version 4.300032, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Docker
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  AnyEvent: 0
  AnyEvent::HTTP: 0
  JSON: 0
  LWP::UserAgent: 0
  Moo: 1.002000
  URI: 0
resources:
  bugtracker: https://github.com/pstuifzand/docker-perl/issues
  homepage: https://github.com/pstuifzand/docker-perl
  repository: https://github.com/pstuifzand/docker-perl.git
version: 0.002002
